import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Section from "../components/Section";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Novex Interior & Furniture</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Banner />
            <Section />
            <Footer />
        </div>
    );
}
